import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../styles/globals.css';
import Header from './components/Header';
import Hero from './components/Hero';
import Services from './components/Services';
import Testimonials from './components/Testimonials';
import Contact from './components/Contact';
import Footer from './components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <Hero />
          <Services />
          <Testimonials />
          <Contact />
        </main>
        <Footer />
      </body>
    </html>
  );
}
